const { Client, Interaction, AttachmentBuilder, EmbedBuilder } = require('discord.js');
const fetchData = require('../../utils/fetch/fetchData');

module.exports = {
    /**
     * 
     * @param {Client} client 
     * @param {Interaction} interaction 
     */

    callback: async(client, interaction) => {
        if(!interaction.inGuild()) {
            interaction.reply({ content: "You can only run this command inside a server.", ephemeral: true });
            return;
        }

        try {
            await interaction.deferReply();

            const Image = await fetchData(`https://inspirobot.me/api?generate=true`);

            const embed = new EmbedBuilder()
                .setColor("Blue")
                .setTitle("Here's a random quote!")
                .setImage(Image)
                .setURL(Image)
                .setFooter({ text: "Generated By An A.I" })

            interaction.editReply({ embeds: [embed] });
        } catch(err) {
            console.log(err);
        }
    },

    name: 'random',
    description: "This is a command that fetches random quotes from an A.I",

    devOnly: false,
    testOnly: false,

    options: [],

    cooldown: 10,

    permissionsRequired: [],
    botPermissions: [],

    deleted: false,
}